services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats_user -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./ewm-stats-service
      dockerfile: Dockerfile
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats_user
      - SPRING_DATASOURCE_PASSWORD=stats_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_password

  ewm-service:
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm_user
      - SPRING_DATASOURCE_PASSWORD=ewm_password